### ISSUE TITLE
recent plans

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#187]
- [x] support column split #30 
- [ ] Support seriation #183 
- [x] Adjust legend labels if they overlap #184 
- [x] support "row_name_labels" and "column_name_labels" #181 
- [x] legend border doesn't work #180 
- [x] automatically recognize whether it is row annotation or column annotation for `anno_*()` functions.
- [x] automatically calculate the position and width of text annotation so users do not need to specify something like `width = max_text_width(...)`.
- [x] HeatmapAnnotation(): `df` does not necessarily locate at the top #166 
- [x] change `combine_name_fun` to other names such as `row_title = "cluster %s"`
- [x] add `anno_lines()`? #161 
- [x] automatically switch to `use_raster = TRUE` for large heatmaps?
- [x] add a `summary()` function for `Heatmap` and `HeatmapList` classes?
- [x] when there are too many legends, should we put them into multiple colums/rows? #46 
- [x] add offset for legends
- [x] selectArea only works in the first heatmap #61 
- [x] grid.dendragram(): when there are more than two leaves #122 
- [x] column title in wrong position when the matrix has zero row. (or automatically detect number of data points when there are only annotations)
- [x] adjust the position of legends #143
- [x] support subsetting a heatmap/heatmaplist #154 
- [x] add a `row_height` and `column_width` argument #109 
- [ ] vectorize oncoprint #86 
- [x] remove the gap between heatmap and bottom annotation #118 (think a better layout)
- [x] Row annotation alignment not correct when using npc units in gap #157
- [x] check devices when `use_raster = TRUE` (`dev.off2()`)
- [x] If row_dend_reorder is set an a vector, row clusters are also reordered by mean reordering scores if rows are split #134
- [x] also add dendrograms between row clusters of rows are split
- [x]  add `anno_joyplot()` and `anno_horizon_chart()`
- [x] append to column/row anntoations
- [ ] `anno_link()` should be applied to the whole heatmap body while not one single row slice.
- [x] `max_text_width()` won't work well if `gp(fontsize)` is a vector
- [x] `anno_horizon()` may add a vertical segment to represent the absolute height
- [x] try to export legend for some of the annotation function
- [x] add fill for titles
- [x] test `anno_text()` with more rotations (one letter text can be drawn by `pch`)
- [x] `anno_simple()` + text labels
- [x] position of legends on the heatmap (centered by annotation + heatmap)
- [x] dendrogram order after `merge.dendrogram()`
- [x] vertical legend: title put on left with rotation 90 degree
- [x]  add left_anntation and right_annotation
- [x] support vertial add using `%v%`

**Comment by crazyhottommy** [comment]
great to see column split is on the to-do list!

**Comment by jokergoo** [comment]
Column split:

```{r}
ht = Heatmap(mat, top_annotation = anno,
	row_split = rep(c("A", "B"), 6), 
	row_names_gp = gpar(col = 2:3), row_gap = unit(2, "mm"),
	column_split = 3,
	column_names_gp = gpar(col = 2:4), column_gap = unit(4, "mm")
)
draw(ht, test = TRUE)
```

![image](https://user-images.githubusercontent.com/449218/43860009-a8da8d1c-9b52-11e8-9dde-2dcc961aa9af.png)

**Comment by crazyhottommy** [comment]
This is awesome, will test and report back!

**Comment by jokergoo** [comment]
It is not finished yet. The package is not usable now.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Thu, Aug 9, 2018 at 5:59 AM +0200, "Ming Tang" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is awesome, will test and report back!

-

**Comment by crazyhottommy** [comment]
will wait then.

**Comment by jokergoo** [comment]
unfished tasks moved to #196
