### ISSUE TITLE
Recent to-do list

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#411]
- [x] write documentation for the support of gridtext
- [x] print important messages #420 
- [x] try to support **gridtext** package #422 
- [x] reorder `row_title`/`column_title` to the clustering or row/column slices when they are set as template #416
- [x] `densityHeatmap()`: add arguments to control whether show the quantile lines #312 
- [x] fix a bug of multiple horizontal legends put below the heatmap #318 
- [x] improve the calculation of break values in the legends #362 
- [x] the first page is still empty (the figure is in the second page) when saving oncoPrint into PDF (maybe other plots) #366 
- [x] UpSet plots: optimize the processing of many sets (current solution consumes huge memory) #320  **UpSet**
- [x] UpSet plots: the "intersect" and "union" seem not correct. Need more tests. #382 **UpSet**
- [x] support a global and over-legends (e.g. gaps between legends) controls for multiple legends #387 #394 
- [x] `grid.dendrogram()`: optimized it solve the problem of "node stack overflow" #400 
- [x] anno_zoom(): position wrongly calculated #433
