### ISSUE TITLE
recent to-do list

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#489]
- [x] Properly align annotation labels #455
- [x] dendrogram allows rendering points on the node #465, won't implement now
- [x] Adjust the positions of legends #468
- [x] position of row names for a list contains both heatmap and row annotations #473
- [x] add a little bit more space between legends #475
- [x] implement a new function `attach_annotation()` #477
- [x] check length of `gap` argument to the number of annotations #485
- [x] subset method is not usable after the layout is initialized. #486
- [x] increase the space between legend title and legend body #488
- [ ] adapt the vignette do describe the new features.
- [ ] Add a new default alteration type "NA" #517 
- [x] add row_slice_reorder argument #526 
- [x] add `boder_gp` argument #524 
- [x] A better way to show raster heatmap #518 
- [x] support cross-slice blocks in `anno_block()` #524，  won't implement now
- [x] separate heatmap legends and row annotation legends? #520 
- [x] guess_align_legend does not work on Rstudio? #531 
- [x] rotate annotation labels
- [x] Add values to heatmap legend that don't appear in heatmap itself #555
- [x] Legend labels with multiple lines #593 
- [x] grid.dendrogram(): do not draw vertical lines when the height of a branch is zero #580
- [x] `row_order` in `draw()` is not collectedly passed to the make_layout() function #579 
- [x] Error: node stack overflow #541
- [x]  space between legends and heatmaps for vertically aligned heatmaps #559 
- [x] setting text align (left, center or right) for titles
- [x] align with ggplot2 plots
