### ISSUE TITLE
Legend-related to-do list

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#632]
- [x] better way to show multiple-interval legends #617
- [ ] legend_grouping set as a list two vectors #618
- [x] reverse the continuous legend #630
