### ISSUE TITLE
To-do-list 2022-02-03

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#865]
- [ ] Check anno_mark() or maybe other functions which reply on absolute size of the device on Jupyter book #837 
- [x] Speed up `Heatmap()` #832
- [ ] Bivariate color scale and legend #839 #812
- [ ] automatically generate legends for more annotations #846
- [ ] anon_block(): draw s subset of blocks #848
- [x] set a proper ylim when all the values are identical #800
- [x] add anno_textbox() #847
- [ ] add title for annotations #879
- [ ] anno_link(): one-to-many, many-to-one, many-to-many #890
- [ ] discrete color mapping for continuous values #880
- [x] if rect_gp = gpar(type = "none"), then show_heatmap_legend = F #885
- [ ] rasterization generates blurry plot for large matrix? #887
- [x] automatically recognize global variables in `cell_fun` and `layer_fun` #892
- [ ] size limit on 'grid_width' for the legend #896
- [ ] `anno_block()` with `anno_mark()` #905 
- [ ] Automatically generate legends for `anno_customize()`? #916
- [ ] support raster annotation graphics #907 
- [x] merge several anno_density into one #919 
- [ ] Missing data in oncoPrint #931
- [ ] UpSet for Genomic Regions, I want to show number of regions, but not the total number of base pairs #914 
- [ ] oncoPrint: cluster_columns = FALSE #908
- [ ] merge several anno_density into one #919 
- [ ] when snpc is set for both width and height, legend is always align to the right of the plot #917
- [ ] white lines appears again in raster images
- [ ] [enhancement] texture and flexible annotation legend placing #939
- [ ] Heatmap with pre-defined dendrogram, margin ordering #949
- [ ] support phylo object #305
- [ ] adjust legend order  #557
- [ ] nested split #1051
- [ ] when `row_split` is set, `row_title` can be a named vector. #1092 
- [ ] use bezier curve for anno_mark and anno_link.
